[40기 황정수] ADD: 소셜 로그인(KAKAO) 기능구현, Modify: users 테이블 kakao_id Type changed to float from int
wecode-bootcamp-korea/40-2nd-DevU-backend pull request #3
Opened 2022-12-27 09:23 UTC by JeongSooHHH

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카카오톡 소셜 로그인 기능 구현
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 카카오톡 소셜 로그인 기능 구현
- kakao_id 데이터 길이에 따른 users Table kakao_id 데이터 타입 변경(int -> float)

<br />

## :: 테스트 결과 이미지

![image](https://user-images.githubusercontent.com/59333783/209644151-4388b25f-f3ff-46c9-8182-85eec83275bf.png)

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/59333783/209644334-18392599-990b-4340-aa20-b21c31f1e477.png">

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-28 03:51 UTC, sangwoong03 commented on package.json
> +    "passport-kakao": "^1.0.1",
passport는 불필요한 모듈이므로 삭제해주세요!

`npm uninstall passport passport-kakao`

```suggestion
```

2022-12-28 03:51 UTC, sangwoong03 commented on db/migrations/20221226104118_create_users_table.sql
> +    kakao_id FLOAT NULL,
카카오 공식문서에 의하면 `kakao_id`는 Long 타입으로 지정되어 있습니다.

![image](https://user-images.githubusercontent.com/93123657/209743113-08fb06de-f6f7-4a57-b389-1084ca753dcc.png)


MySQL에서 지원하는 Numeric 데이터 타입 중 integer에 관련된 공식 문서를 보게 되면 다음과 같이 설명하고 있습니다.

![image](https://user-images.githubusercontent.com/93123657/209743240-4d9cdc09-862a-4f3a-aabe-57d1bac85d34.png)

integer 필드의 범위를 넘어서는 `kakao_id`가 반환될 수 있기 때문에 float 보다는 int 혹은 bigint 필드를 지정하는 것이 더 좋을 것 같습니다.

2022-12-28 03:51 UTC, sangwoong03 commented on app.js
> +  res.json({ message: "pong!" });
정수님, `next` argument 를 넣은 이유가 있을까요?

2022-12-28 03:51 UTC, sangwoong03 commented on .env.sample
> +KAKAO_URL = REDIRECT
`KAKAO_ID`, `KAKAO_URL` 해당 변수 사용하지 않으면 삭제해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on .env.sample
> +JWT_SECRET=HIGH
해당 값을 유추할 수 있을 정도로 작성해주면 좋을 것 같아요!

```suggestion
ALGORITHM=ALGORITHM_HASH
JWT_SECRET=LONG_SECRET_KEY
```

2022-12-28 03:51 UTC, sangwoong03 commented on src/controllers/userController.js
> +	console.log(kakaoToken, '=========================')
불필요한 console.log() 는 삭제해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on src/controllers/index.js
> +};
routes/userRouter.js 파일에서 `userController.signInKakao()`로 컨트롤러 함수를 호출하고 있습니다.

index.js 파일에서 모든 모듈을 모아서 내보내는 기능을 사용하지 않는 것 같습니다.

현재 모든 레이어 폴더마다 index.js를 적용할 수 있도록 함수 호출 부분을 수정하거나, index.js 파일을 사용하지 않는 방향으로 수정해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on src/routes/userRouter.js
> +router.post('/kakao/signin', userController.signInKakao)
토큰을 확인하는 미들웨어 적용이 누락된 것 같습니다!

2022-12-28 03:51 UTC, sangwoong03 commented on src/services/userService.js
> +    const profileImage = data.properties.profile_image;
`nickname` `profile_image`도 `kakao_account` 데이터 내부에 있는 것 같은데 다시 확인부탁드립니다!

2022-12-28 03:51 UTC, sangwoong03 commented on src/services/userService.js
> +    if (!kakaoId || !email) throw new error("KEY_ERROR", 400);
`kakao_id` 가 없는 경우는 없을 것 같습니다.

아마 그 전에 카카오 토큰으로 해당 유저를 받아올 수 없다는 에러메시지가 반환될 것 같습니다.

해당 예외처리를 다시 한번 고민해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on src/services/userService.js
> +    console.log('user' , user)
불필요한 console.log() 는 삭제해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on src/services/userService.js
> +    )
토큰의 payload에 카카오 아이디를 직접 넣기 보단 서버에서 생성된 유저의 id 값을 넣도록 수정해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on src/utils/auth.js
> +	}
에디터 상에서 들여쓰기 확인해주세요!

2022-12-28 03:51 UTC, sangwoong03 commented on src/utils/auth.js
> +  const decoded = await promisify(jwt.verify)(accessToken, process.env.JWT_SECRET);
promisify 사용 이유에 대해 커멘트로 설명 부탁드립니다.

2022-12-28 03:51 UTC, sangwoong03 commented on src/models/userDao.js
> +		email,
에디터 상에서도 들여쓰기 문제 여부 확인해주세요! (없으면 github 자체의 문제이므로 패스하겠습니다.)

2022-12-28 03:51 UTC, sangwoong03 commented on src/models/userDao.js
> +}
토큰을 발행할 때 주입하는 payload에 user의 id 값을 주입한 이후, 해당 함수에서도 user의 id 값을 통해 데이터를 조회할 수 있도록 수정해주세요.

user의 id도 반환하는 것이 좋을 것 같습니다!

```suggestion
const getUserById = async (userId) => {
    const [user] = await appDataSource.query(`
    SELECT
        id,
        kakao_id,
        email,
        nickname,
        profile_image
    FROM users
    WHERE id=?`
    , [userId]
    )
    return user
} 
```

2022-12-28 03:51 UTC, sangwoong03 commented on src/utils/error.js
> +}
`globalErrorHandler` 함수가 작성은 되었지만 아직 사용이 되지 않고 있습니다.

app.js에서 사용될 수 있도록 반영해주세요!

2022-12-28 04:49 UTC, JeongSooHHH commented on package.json
> +    "passport-kakao": "^1.0.1",
.

2022-12-28 04:49 UTC, JeongSooHHH commented on package.json
> +    "passport-kakao": "^1.0.1",
완료하였습니다.

2022-12-28 04:52 UTC, JeongSooHHH commented on db/migrations/20221226104118_create_users_table.sql
> +    kakao_id FLOAT NULL,
INT 이용시 범위초과 오류가 발생하여서 bigint로 수정 완료하였습니다.

2022-12-28 05:00 UTC, JeongSooHHH commented on app.js
> +  res.json({ message: "pong!" });
불필요 내용으로 삭제 완료하였습니다. 
( 어떤 유튜브에서 쓰지 않아도 습관적으로 넣어 두라고 하였어서 사용하였었습니다.)

2022-12-28 05:01 UTC, JeongSooHHH commented on .env.sample
> +KAKAO_URL = REDIRECT
삭제 완료하였습니다.

2022-12-28 05:03 UTC, JeongSooHHH commented on .env.sample
> +JWT_SECRET=HIGH
반영 완료하였습니다.

2022-12-28 05:04 UTC, JeongSooHHH commented on src/controllers/userController.js
> +	console.log(kakaoToken, '=========================')
삭제 완료하였습니다.

2022-12-28 05:05 UTC, JeongSooHHH commented on src/services/userService.js
> +    console.log('user' , user)
삭제 완료하였습니다.

2022-12-28 05:17 UTC, JeongSooHHH commented on src/services/userService.js
> +    const profileImage = data.properties.profile_image;
<img width="848" alt="image" src="https://user-images.githubusercontent.com/59333783/209761111-2f1dd583-92e0-4112-b290-47a45d82dcc4.png">

properties와 kakao_account 이중으로 들어가 있어서 통일성을 위해 kakao_account단으로 수정하도록 하겠습니다.

const name = data.kakao_account.profile.nickname;
const email = data.kakao_account.email;
const profileImage = data.kakao_account.profile.profile_image;

2022-12-28 05:22 UTC, JeongSooHHH commented on src/models/userDao.js
> +}
반영 완료하였습니다.

2022-12-28 05:23 UTC, JeongSooHHH commented on src/models/userDao.js
> +		email,
git에서 발생한 오류인것 같습니다. 패스하겠습니다.

2022-12-28 07:00 UTC, JeongSooHHH commented on src/services/userService.js
> +    if (!kakaoId || !email) throw new error("KEY_ERROR", 400);
불필요 코드로 생각되어 해당구문  제거하였습니다.

if (!kakaoId || !email) throw new error("KEY_ERROR", 400);

2022-12-28 07:25 UTC, JeongSooHHH commented on src/services/userService.js
> +    )
반영하였습니다.

2022-12-28 07:26 UTC, JeongSooHHH commented on src/utils/auth.js
> +	}
들여쓰기 수정하였습니다.

2022-12-28 07:35 UTC, JeongSooHHH commented on src/utils/error.js
> +}
반영하였습니다.

const { globalErrorHandler } = require("./src/utils/error");
app.use(globalErrorHandler)

2022-12-28 08:09 UTC, JeongSooHHH commented on src/utils/auth.js
> +  const decoded = await promisify(jwt.verify)(accessToken, process.env.JWT_SECRET);
토큰 발급 시 콜백 함수(Executer)를 통해 카카오톡 api 와 네트워크 통신을 하기 위하여 사용했습니다.

2022-12-28 14:11 UTC, JeongSooHHH commented on src/controllers/index.js
> +};
index 파일 사용하지 않는 방향으로 반영하였습니다.

2022-12-29 23:45 UTC, sangwoong03 requested changes
<img width="537" alt="image" src="https://user-images.githubusercontent.com/93123657/210021162-d169dd4f-d1e9-41a0-8b48-b1102ff5f1a4.png">

제가 확인할 때는 rebase가 안된 것 같네요 정수님!
`git rebase -i main`
다시 한 번 확인해주세요~

2022-12-29 23:45 UTC, sangwoong03 commented on src/controllers/userController.js
> +    const kakaoToken = req.headers.authorization;
토큰이 없는 경우 로그인이 필요할 것 같네요!

해당 예외처리를 할 수 있는 코드를 추가해주세요!

2022-12-29 23:45 UTC, sangwoong03 commented on src/services/userService.js
> +            Authorization: `Bearer ${kakaoToken}`,
공식문서에서 `Content-Type` 도 설정하도록 되어있으니 참고하여 수정해주세요

2022-12-29 23:45 UTC, sangwoong03 commented on src/services/userService.js
> +    console.log('result', result)
불필요한 console.log() 코드는 push 전 확인하는 습관을 가져주세요

2022-12-29 23:45 UTC, sangwoong03 commented on src/utils/auth.js
> + 	const decoded = await promisify(jwt.verify)(accessToken, process.env.JWT_SECRET);
> 토큰 발급 시 콜백 함수(Executer)를 통해 카카오톡 api 와 네트워크 통신을 하기 위하여 사용했습니다.

다음과 같이 설명하셨는데 promisify 모듈이 여기서 필요한 것인지 다시 한번 고민해주세요. 

또한 해당 코드가 카카오 api를 호출하는 것이 맞는지도 확인해주세요.

해당 코드는 서버에서 발급한 토큰을 검증하는 코드입니다.

async-await 키워드를 통해 이미 promise 함수의 비동기 연산을 처리하고 있습니다.

2022-12-30 01:53 UTC, JeongSooHHH commented on src/services/userService.js
> +    console.log('result', result)
네 숙지하겠습니다!

2022-12-30 02:36 UTC, JeongSooHHH commented on src/services/userService.js
> +            Authorization: `Bearer ${kakaoToken}`,
Content-Type 추가하였습니다.

    const result = await axios.get("https://kapi.kakao.com/v2/user/me", {
        headers: {
            Authorization: `Bearer ${kakaoToken}`,
            "Content-type": "application/x-www-form-urlencoded;charset=utf-8"
        },

2022-12-30 07:49 UTC, JeongSooHHH commented on src/controllers/userController.js
> +    const kakaoToken = req.headers.authorization;
try catch 로 예외처리 추가하였습니다.

2022-12-30 08:22 UTC, sangwoong03 requested changes
정수님 고생하셨습니다!

로그인 성공했을 경우 테스트 코드 작성해주시죠! ㅎㅎ

2022-12-31 07:43 UTC, JeongSooHHH commented
프론트와 붙이는 도중 미들웨어 작동 및 토큰 발급 기능이 원활하지 않아 코드 수정하여 다시 푸시하였습니다!

2023-01-03 05:35 UTC, JeongSooHHH reviewed
![Screen Shot 2023-01-03 at 2 27 44 PM](https://user-images.githubusercontent.com/59333783/210304735-be3c4d4f-8cb1-4e64-9e41-89a79725b15c.png)

2023-01-03 06:42 UTC, sangwoong03 requested changes
컨플릭트만 해결해주세요!

2023-01-03 08:45 UTC, sangwoong03 approved these changes
DB mirgraion 파일 다시 push 해주세요 👍

2023-01-03 08:45 UTC, merged