[40기 황정수] ADD: 메인 페이지 구현(전체 상품목록 포함)
wecode-bootcamp-korea/40-2nd-DevU-backend pull request #4
Opened 2023-01-02 05:25 UTC by JeongSooHHH

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 전체 도서 검색 및 메인 페이지 API 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 전체 도서 검색 및 메인 페이지 API 구현

<br />

## :: 테스트 결과 이미지
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/59333783/210197453-537fb65d-7be6-4dc7-b59b-cb4b424caaac.png">

<br />

## :: 기타 질문 및 특이 사항

2023-01-02 06:26 UTC, sangwoong03 requested changes

2023-01-02 06:26 UTC, sangwoong03 commented on src/controllers/bookController.js
> +  res.status(200).json(books);
함수가 종료되는 것을 의미하는 return 키워드를 작성해주세요!
```suggestion
  return res.status(200).json(books);
```

2023-01-02 06:26 UTC, sangwoong03 commented on src/controllers/bookController.js
> +});
함수명이 조금 불명확한 것 같습니다.
book의 id 값으로 특정 값을 조회하는 것이라면 다음과 같이 수정하면 좋을 것 같습니다.

```suggestion
const getBooksById = catchAsync(async (req, res) => {
  const bookId = req.params.id;
  const books = await bookService.getBooksByMain(bookId);
  return res.status(200).json(books);
});
```

2023-01-02 06:26 UTC, sangwoong03 commented on src/controllers/bookController.js
> +  getBooksByMain
함수명 수정하면서 export 하는 부분도 수정해주세요!

2023-01-02 06:26 UTC, sangwoong03 commented on src/routers/index.js
> +router.use("/books", bookRouter);
마이너하지만 가독성을 위해 한줄 띄어주면 좋겠네요!
```suggestion
const bookRouter = require("./bookRouter");

router.use("/books", bookRouter);
```

2023-01-02 06:26 UTC, sangwoong03 commented on src/routers/bookRouter.js
> +router.get("/main_categories/:id", bookController.getBooksByMain);
RESTful API에서는 `_` 언더바 대신 `-` 하이픈을 쓰는 것을 권장합니다.

만약 누군가에게 우리 서비스의 url을 전달하는 경우, 링크 자체를 전달하면서 자동으로 밑줄이 생기는 현상을 본 적이 있을 것입니다.

_ 언더바가 포함되면 자동으로 생성된 밑줄과의 혼선이 생길 수 있어 엔드포인트에는 작성하지 않는 것이 좋겠습니다.

books의 id 값으로 특정 리소스를 조회하는 것이기 때문에 `http://localhost:3000/books/1` 과 같은 엔드포인트가 가장 적절해보입니다.
```suggestion
router.get("/:bookId", bookController.getBooksByMain);
```

2023-01-02 06:26 UTC, sangwoong03 commented on src/services/bookService.js
> +};
해당 부분도 함수명 수정하면 좋을 것 같습니다!

또한 위의 함수처럼 `await bookDao.getBooksByMain(id);` 부분을 바로 return 해도 좋을 것 같습니다.

```suggestion
const getBooksByMain = async id => {
  return await bookDao.getBooksByMain(id);
};
```

2023-01-02 06:26 UTC, sangwoong03 commented on src/models/bookDao.js
> +  );
- 우선 들여쓰기 수정해주세요!
- 컬럼명을 그대로 가져오게되면 snake_case로 필드를 반환합니다. 프론트엔드 분들과 소통하여 이 부분 통일하면 좋을 것 같습니다.

```suggestion
  const resultAll = await appDataSource.query(`
    SELECT 
      id,
      sub_category_id, // as subCategoryId 혹은 snake_case 유지  
      title,
      image_url,
      published_date,
      offline_price,
      online_price,
      author,
      publisher,
      description,
      publisher_review,
      list,
      created_at
    FROM books
    `);
```

2023-01-02 06:26 UTC, sangwoong03 commented on src/models/bookDao.js
> +};
- 해당 부분도 들여쓰기 수정해주세요!
- 와일드카드 * asterisk를 사용하는 것도 좋지만 특정 컬럼을 직접 작성해서 조회할 수 있도록 수정해주세요!
데이터를 관리하기 위한 컬럼이 포함되어 불필요한 값을 전달할 수 있고 해당 행위를 통해 큰 차이는 아니더라도 성능도 저하될 가능성이 있을 것 같습니다.
- 인자로 받아온 변수를 직접 기입하지 말고 `?` mapping을 사용하도록 수정해주세요!
- right join 하는 부분의 조건을 다시 한 번 고민해주세요!

2023-01-02 06:35 UTC, JeongSooHHH commented on src/controllers/bookController.js
> +  res.status(200).json(books);
수정 완료하였습니다!

2023-01-02 11:56 UTC, sangwoong03 requested changes
정수님! mainCategoryId 값을 받아 특정 책들을 조회할 수 있는 테스트 케이스 하나 작성 가능하실까요??

2023-01-02 11:56 UTC, sangwoong03 commented on src/controllers/bookController.js
> +  const bookId = req.params.mainId;
정수님~!!!! 이 부분 저랑 mainCategoryId 받기로 결정했는데 반영이 안되어있네요.
해당 부분 반영할 수 있도록 수정해주세요.

2023-01-02 11:56 UTC, sangwoong03 commented on src/models/bookDao.js
> +      m.id as mainCategoryId
해당 부분도 제가 이해를 돕기 위한 alias 적용 부분이었습니다!
데이터를 어떻게 보내줄 지 백엔드 팀에서 결정하면 되는 사안입니다.

2023-01-02 11:56 UTC, sangwoong03 commented on src/routers/bookRouter.js
> +router.get("/:mainId", bookController.getBooksById);
mainCategoryId를 받는 것이 명확하게 보일 수 있도록 수정해주세요.
```suggestion
router.get("/:mainCategoryId", bookController.getBooksByMainCategoryId);
```

2023-01-02 11:56 UTC, sangwoong03 commented on src/controllers/bookController.js
> +const getBooksById = catchAsync(async (req, res) => {
mainCategoryId 받아서 특정 리소스 조회하는 의미가 담긴 함수명을 적용해주세요!

2023-01-02 11:56 UTC, sangwoong03 commented on src/services/bookService.js
> +};
불필요한 띄워쓰기 한번 더 확인해주시고, 함수명도 더 명확하게 수정해주세요!

2023-01-05 09:22 UTC, sangwoong03 approved these changes
LGTM 👍

2023-01-05 09:22 UTC, merged