[40기 황정수] ADD: 리스트 페이지 및 특정 도서 검색 api 구현
wecode-bootcamp-korea/40-2nd-DevU-backend pull request #5
Opened 2023-01-02 05:49 UTC by JeongSooHHH

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

리스트페이지 api 및 책 제목 기반 검색 기능 구현

<br />

리스트페이지 api 및 책 제목 기반 검색 기능 구현

<br />
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/59333783/210198453-213a6ac6-3752-451e-a9a3-e15b3d80118d.png">

<br />

## :: 기타 질문 및 특이 사항

2023-01-02 06:39 UTC, sangwoong03 requested changes

2023-01-02 06:39 UTC, sangwoong03 commented on db/migrations/20221226103537_create_books_table.sql
> +    online_price INT NOT NULL,
데이터베이스 관련 pr은 확인 후 바로 merge 할 수 있도록 수정해주세요!

다만 price 컬럼은 integer 보다 decimal 이 적절할 것 같습니다.

참고자료: https://www.tutorialspoint.com/which-mysql-type-is-most-suitable-for-price-column

2023-01-02 06:39 UTC, sangwoong03 commented on src/models/bookDao.js
> +      sub_category_id = '${id}'
인자로 받은 데이터를 직접 주입하지 말고 `?` mapping 할 수 있도록 수정해주세요!

2023-01-02 06:39 UTC, sangwoong03 commented on src/models/bookDao.js
> +		SELECT
들여쓰기 수정해주세요!

2023-01-02 06:39 UTC, sangwoong03 commented on src/models/bookDao.js
> +		WHERE
여기도 들여쓰기 수정해주세요!

2023-01-02 06:39 UTC, sangwoong03 commented on src/models/bookDao.js
> +      title LIKE '%${title}%'
해당 부분도 `?`를 활용할 수 있도록 수정해주세요!

2023-01-02 06:39 UTC, sangwoong03 commented on src/routers/bookRouter.js
> +router.get("/sub_categories/:id", getBooksById);
RESTful API에서는 _ 언더바 대신 - 하이픈을 쓰는 것을 권장합니다.

만약 누군가에게 우리 서비스의 url을 전달하는 경우, 링크 자체를 전달하면서 자동으로 밑줄이 생기는 현상을 본 적이 있을 것입니다.

_ 언더바가 포함되면 자동으로 생성된 밑줄과의 혼선이 생길 수 있어 엔드포인트에는 작성하지 않는 것이 좋겠습니다.

books의 id 값으로 특정 리소스를 조회하는 것이기 때문에 http://localhost:3000/books/1 과 같은 엔드포인트가 가장 적절해보입니다.

여기서는 `getBooksByCategoryId`라는 함수명이 좋을 것 같네요!
```suggestion
router.get("/subCategories/:id", getBooksByCategoryId);
```

2023-01-02 06:39 UTC, sangwoong03 commented on src/services/bookService.js
> +  return books;
이전 pr과 통일성을 맞추기 위해 다음과 같이 수정해주세요!
```suggestion
  return await bookDao.getBooksById(id);
```

2023-01-02 06:39 UTC, sangwoong03 commented on src/services/bookService.js
> +};
이전 pr과 통일성을 맞추기 위해 다음과 같이 수정해주세요!
```suggestion
const getBooksByName = async (title) => {
  return await bookDao.getBooksByName(title);
};
```

2023-01-02 06:39 UTC, sangwoong03 commented on src/controllers/bookController.js
> +const getBooksById = catchAsync(async (req, res) => {
함수명 수정 적용해주세요!
```suggestion
const getBooksByCategoryId = catchAsync(async (req, res) => {
```

2023-01-02 06:39 UTC, sangwoong03 commented on src/controllers/bookController.js
> +  const id = req.params.id;
변수명도 수정해주세요~!
```suggestion
  const subCategoryId = req.params.id;
```

2023-01-02 06:39 UTC, sangwoong03 commented on src/models/bookDao.js
> +      created_at
해당 부분도 확인해주세요!
컬럼명을 그대로 가져오게되면 snake_case로 필드를 반환합니다. 프론트엔드 분들과 소통하여 이 부분 통일하면 좋을 것 같습니다.

2023-01-02 08:17 UTC, JeongSooHHH commented on db/migrations/20221226103537_create_books_table.sql
> +    online_price INT NOT NULL,
수정 완료하였습니다!

2023-01-02 08:22 UTC, JeongSooHHH commented on src/routers/bookRouter.js
> +router.get("/sub_categories/:id", getBooksById);
수정 완료하였습니다!

2023-01-02 08:23 UTC, JeongSooHHH commented on src/services/bookService.js
> +  return books;
수정 완료하였습니다!

2023-01-02 08:24 UTC, JeongSooHHH commented on src/services/bookService.js
> +};
수정 완료하였습니다!

2023-01-02 08:24 UTC, JeongSooHHH commented on src/controllers/bookController.js
> +const getBooksById = catchAsync(async (req, res) => {
반영 완료하였습니다!

2023-01-02 08:25 UTC, JeongSooHHH commented on src/controllers/bookController.js
> +  const id = req.params.id;
수정 완료하였습니다!

2023-01-02 08:26 UTC, JeongSooHHH commented on src/models/bookDao.js
> +      sub_category_id = '${id}'
수정완료하였습니다!

2023-01-02 09:03 UTC, JeongSooHHH commented on src/models/bookDao.js
> +		WHERE
![image](https://user-images.githubusercontent.com/59333783/210211375-0afede53-582d-4b09-9278-263ef0a81ad8.png)
에디터 에러인것 같습니다!

2023-01-02 09:14 UTC, JeongSooHHH commented on src/models/bookDao.js
> +      title LIKE '%${title}%'
수정 완료하였습니다!

2023-01-02 09:18 UTC, JeongSooHHH commented on src/models/bookDao.js
> +      created_at
이미 머지가 되어서 최대한 수정 안하는 쪽으로 진행될거같습니다!
해당부분 기억하고 있다가 다음에는 반영하여 코딩토록 하겠습니다!

2023-01-02 09:51 UTC, JeongSooHHH commented on src/models/bookDao.js
> +		SELECT
반영 완료하였습니다.

2023-01-02 12:00 UTC, sangwoong03 commented on src/models/bookDao.js
> +      created_at
데이터베이스의 컬럼을 바꾸는 것이 아니라 alias를 통해 컬럼명을 변경하여 반환할 수 있습니다!
해당 내용 확인해서 적용해주시면 좋을 것 같습니다!

2023-01-02 12:04 UTC, sangwoong03 reviewed
정수님 고생하셨습니다.
이 API도 테스트 코드 도전해주시죠!

2023-01-02 12:04 UTC, sangwoong03 commented on db/migrations/20221226103537_create_books_table.sql
> +    online_price DECIMAL(10,0) NOT NULL,
PR 분리 도전해보는 거 어려우실까요? ㅎㅎ

2023-01-05 10:24 UTC, sangwoong03 approved these changes
고생하셨습니다!

2023-01-05 10:24 UTC, merged